### ISSUE TITLE
Maquetación Landing Pública Sumate a Sadia

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Sadia#1]
@FAAREIA te paso el PSD final aprobado para armar la página:

https://wetransfer.com/downloads/2faabef2e0de627ae743e6719aa67b4c20161116194018/7f807b

La home final sería así:

![landing7](https://cloud.githubusercontent.com/assets/6719872/20364539/4be1cb46-ac22-11e6-9659-8cd451201938.jpg)

La página del video personalizado tenés acá el editable:

https://wetransfer.com/downloads/a769134c82a643cda4b016ed01a6641720161116212737/2963af

El editable del mailing acá:

https://wetransfer.com/downloads/85f201dd2c7f35584f65f783760c4edd20161116223224/910dd4

Solo te pido que el texto del mailing que dice:

"Creaste tu receta de frankfurter, este es el video"

lo reemplaces por:

"Sos el creador de un frankfurter único. Miralo en tu video:"

Confirmame si mañana podés arrancar o te falta algún material.

abrazo

**Comment by LeandroBraier** [comment]
@FAAREIA actualicé el ticket. Ya tenés los 3 editables para maquetar.

abrazo

**Comment by LeandroBraier** [comment]
@FAAREIA avisame si recibiste y pudiste ver algo de esto.

abrazo

**Comment by FAAREIA** [comment]
http://www.benteveo.tv/sadia/sitio/
http://www.benteveo.tv/sadia/sitio/video.html

Falta lo responsivo todavía pero voy a avanzar con el mailing.

**Comment by FAAREIA** [comment]
http://www.benteveo.tv/sadia/mailing/video/video.html
No esta preparado para mandar al usuario final pero si para ir probando. Faltaría poner la imagen que va a ir en representación del video.

**Comment by LeandroBraier** [comment]
Buenisimo @FAAREIA !

Te paso feedback mínimo pero estamos muy bien:

http://www.benteveo.tv/sadia/sitio/

. Tenés que embeber el sitio de Sadia, no el de Paty jeje: https://web.facebook.com/SadiaUruguay/
Lo mismo en el footer. Linkealo ahi.

. Hay posibilidad de poner el spot un poco más chico para que se empiecen a ver antes el mapa y el embed de facebook?

http://www.benteveo.tv/sadia/sitio/video.html Perfecto!

http://www.benteveo.tv/sadia/mailing/video/video.html

No aplicaste lo que te había pedido.

> Solo te pido que el texto del mailing que dice:
> "Creaste tu receta de frankfurter, este es el video"
> lo reemplaces por:
> "Sos el creador de un frankfurter único. Miralo en tu video:"

Con eso estamos. Puede ser para el lunes.

abrazo

**Comment by FAAREIA** [comment]
Ahi esta listo Lea.
Con respecto a que se pueda ver antes el mapa y el fb, teniendo en cuenta que el header es alto y el video no puede achicarse porque implicaría achicar todo lo demás, podríamos poner el video debajo del mapa y el fb. ¿Qué decis?

**Comment by mkreyness** [comment]
Avisen cuando ya lo puedo tomar como definitivo y pasar al servidor

**Comment by LeandroBraier** [comment]
Gracias @FAAREIA !

@mkreyness estos 2 ya están OK para pasar al servidor:

http://www.benteveo.tv/sadia/sitio/ 
http://www.benteveo.tv/sadia/sitio/video.html 

@FAAREIA del mailing te pido un cambio muy chiquito nomás. Cambiá el "Haz clic" por "Hacé clic" porfa.

Con eso estamos. Gracias a los dos!

abrazo

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Perfecto @FAAREIA ! Porfa crearías el template en Mailchimp y una base de mails que ya permite el MERGE? Podés ver lo que hiciste para Paty y replicarlo porque las bases y los templates siguen en Mailchimp.

**Comment by LeandroBraier** [comment]
@mkreyness te paso el video para reemplazar el spot que estamos usando actualmente en la landing. Vos lo cambiás?

`<iframe src="https://player.vimeo.com/video/193607561" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>`

**Comment by mkreyness** [comment]
La landing esta apagada, la prendo, remplazo, pruebo, te muestro, y vuelvo a apagar, ok ?

**Comment by LeandroBraier** [comment]
Dale porfa. Pero primero probá si te permite embeber este mejor:

`<iframe src="https://www.facebook.com/plugins/video.php?href=https%3A%2F%2Fwww.facebook.com%2FSadiaUruguay%2Fvideos%2F562694633920300%2F&show_text=0&width=560" width="560" height="315" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true" allowFullScreen="true"></iframe>`

Si se puede ese mejor.

**Comment by mkreyness** [comment]
ok, tarda un rato en arrancar...

**Comment by LeandroBraier** [comment]
Porque es de Facebook, puede ser? Lo que pasa es que la marca no tiene YouTube, por eso estaba intentando con Facebook y sino vamos con nuestro Vimeo.

**Comment by mkreyness** [comment]
no, lo que tarda en arrancar es el server en Amazon, porque tengo que cambiarle el IP al DNS (al apagarse pierde el IP).

**Comment by mkreyness** [comment]
Listo
http://sumateasadia.com.uy
y si no te anda, entra por el IP:
http://35.165.73.49

**Comment by LeandroBraier** [comment]
Quedó perfecto MK! Apagá el servidor nomás y te aviso cuando arrancamos.

abrazo

**Comment by mkreyness** [comment]
ok

**Comment by LeandroBraier** [comment]
@mkreyness prendamos el servidor nomás!! Avisame porfa cuando esté arriba.

**Comment by mkreyness** [comment]
esta prendido, pero no hay que hacer otros cambios en la pagina ? Tiene una fecha que ya paso.

**Comment by LeandroBraier** [comment]
Tenés razón y además Eze me pidió apagarlo de vuelta hasta mañana a la tarde. Mil disculpas. Volvamos a off porfa.

**Comment by mkreyness** [comment]
Apagando.

**Comment by LeandroBraier** [comment]
Gracias MK! Mañana a la tarde lo subimos de nuevo, ya te voy a avisando,
pero yo te lo recuerdo por github no te preocupes. También mañana te voy a
pasar la fecha y coordenadas de Google Map definitivas para la activación.

abrazo y gracias

**Comment by mkreyness** [comment]
ok

**Comment by LeandroBraier** [comment]
@mkreyness te paso los datos para cuando subamos:

**El 3 de Diciembre desde las 16 hs estaremos en Supermercado Disco** 

Supermercado DISCO MAGARINIOS CERVANTES 2052 ESQ. AV. ITALIA

https://www.google.com.br/maps/place/Supermercado+Disco/@-34.886055,-56.1445065,16.5z/data=!4m5!3m4!1s0x0:0x4eb63df585dac29!8m2!3d-34.8876064!4d-56.1409065

abrazo

**Comment by LeandroBraier** [comment]
Buen día @mkreyness ! Cómo va?

Te paso los datos de supermercados para actualizar en la landing:

EL 17 Y 18 DE DICIEMBRE ENCONTRANOS EN SUPERMERCADO DEVOTO, AVENIDA ROOSEVELT PARADA 10, PUNTA DEL ESTE, DE 16 HS A 21 HS

Consulta aparte: tenés idea en qué status están los videos de Sadia de Uruguay del fin de semana? No los veo subidos en el CMS. Se los pido a Eze no? O está pendientes de algún proceso?

**Comment by mkreyness** [comment]
Enseguida lo actualizo.
Y no, a mi nadie me mando nada para subir al server, y no creo que lo esten subiendo desde Uruguay.
Los anteriores Eze me los habia mandado por WeTransfer, pero esta vez no me llego nada.

**Comment by LeandroBraier** [comment]
Gracias MK! Ya le reclamé a Eze y me dijo que aun no se los mandan de Uruguay. Apenas los tenemos te los mandamos. abrazo

**Comment by mkreyness** [comment]
ya esta actualizada la fecha

**Comment by LeandroBraier** [comment]
Muchas gracias @mkreyness !

**Comment by LeandroBraier** [comment]
@mkreyness cambio de último momento.

El super no es el mismo.

EL 17 Y 18 DE DICIEMBRE ENCONTRANOS EN MACROMERCADO CARRASCO, AVENIDA AL PARQUE ROOSEVELT 2495, CIUDAD DE LA COSTA DE 16 A 21 HS

<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3273.4679806495196!2d-56.02451508507461!3d-34.86959308039143!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x959f889e53547933%3A0x926ea5a685506092!2sMacromercado+Carrasco!5e0!3m2!1sen!2sar!4v1481644967381" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>

abrazo

**Comment by LeandroBraier** [comment]
Marce, apenas puedas actualizalo. 

Aprovecho a consultarte porque hay un video que no está corriendo, no sé por qué. Es justo de los que están en la landing.

http://sumateasadia.com.uy/video.html?numero=7d28e6531a93f77c30b6c0fece2f00bc4456fc4a

**Comment by mkreyness** [comment]
El video a mi me funciona lo mas bien. No sera de esos que tenian el audio incompatible con Mac ?
FIjate por favor si los nuevos que cargue ahora te funcionan (se supone que Valen hizo el cambio en la maquina que esta en Uruguay el dia que estuvo conectada).

**Comment by LeandroBraier** [comment]
Tenés razón. A mi también. Lo que no me andaba era la URL. No sé qué pasaba ahora todo joya. Gracias!
