### ISSUE TITLE
Pequeño sistema Sadia para Ironman

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Sadia#2]
@mkreyness cómo estás?

Al final me aprobaron lo que hablamos el otro día, así que paso a explicar.

RESUMEN
Estamos haciendo una activación para Sadía en la carrera IRONMAN, que es el triatlón más competitivo del mundo que se hace en Punta del Este.
La activación consiste en esto:

<img width="1158" alt="captura de pantalla 2016-11-22 a las 12 11 38 p m" src="https://cloud.githubusercontent.com/assets/6719872/20528186/ec155930-b0a9-11e6-8978-a33936dfa040.png">

PROCESO HABLADO CON MK

1- Equipo de producción toma las fotos manualmente con la cámara fija en un trípode. La promotora anota numero de corredor y mail a mano en una tablet.

2- Equipo de producción renombramos las imágenes con el mail reemplazando la ARROBA por un + y agrega en un excel a número de corredor y el mail, el tiempo que realizó cada uno.

**3- Valen le agrega el tiempo a cada foto en el servidor manteniendo el nombre de la foto.

4- Valen sube las fotos terminadas al servidor.

5- MK hace el proceso que manda los mails según el nombre de cada archivo.**

Fecha en que necesitamos tener lista la parte de uds del sistema: **Viernes 25/11**

Me confirman si llegamos ok?

abrazo

**Comment by mkreyness** [comment]
Necesito la maquetacion del mail para saber donde voy a meter la foto.
Ejemplo de como deberia llamarse la foto: "leandro+benteveo.tv.jpg"
Si tengo la maquetacion a mas tardar mañana a la mañana, yo llego bien.

**Comment by FAAREIA** [comment]
El mailing que decis [es este](http://www.benteveo.tv/sadia/mailing/video/video.html) no?
Por otra parte, no usaría el caracter "+" en ningun nombre de archivo

**Comment by LeandroBraier** [comment]
Jeje no, no es el mismo pero la estructura seria idéntica Fede. Este
mailing te lo tengo que pedir todavia.tñ

Te sirve como maqueta para ir avanzando MK?

**Comment by mkreyness** [comment]
La foto iria donde dice "video" ?
El asunto con el nombre de archivo es que lamentablemente como aca no va a haber base de datos (ni presupuesto para que la haya) tengo que tener EL MAIL DEL TIPO en el nombre del archivo,  unica cosa accesible. Y si ponen @ en el nombre de archivo me parece que va a ser peor.
Esto no se va a ver web, no va a estar hosteado sino que va a ir incrustado en el mail, no va a tener nombre visible.

**Comment by LeandroBraier** [comment]
@mkreyness y @FAAREIA disculpen la desprolijidad de este pedido sin maquetación de mailing previa. Ahora le paso a @FAAREIA en ticket aparte el pedido para el mailing final, que es más que simple.

abrazo

**Comment by mkreyness** [comment]
estoy probando de mandar fotos "inline" en el mail y no se ven bien, porque dependiendo del cliente que tenga c/u puede ser que las muestre en su lugar o aparte como attaches.
Y si las hosteamos nomas en el sitio de benteveo ? Total cuantas van a ser ?
Otro tema con esto: con todas las normas de seguridad que hubo que poner en Duplika por eso de que salian mails truchos, solo me deja mandarlos si uso un email valido (por ejemplo, info@benteveo.tv) o sea, no puedo mandarlo "como si" yo fuera sadia.com.uy o cosa por el estilo. Que hacemos con eso ? Puedo fingirle el nombre (ej, que diga "Panchismo Sadia" <info@benteveo.tv>) pero igual es una porqueria.
Y finalmente: no te olvides pasarme el "Asunto:" del mail. Acordate que es fijo, no tengo el nombre del tipo ni nada (low cost).

**Comment by LeandroBraier** [comment]
Respuesta: Ok, hosteemoslas en el servidor de benteveo (lo más comprimidas posible) pero incluyamos en el mailing la posibilidad de compartir y descargar. Que no haya una página de video.

Asunto: Sadia te felicita por tu tiempo de llegada en Ironman! Compartí tu foto

**Comment by mkreyness** [comment]
videos no hay.
El tamaño de la foto depende de como las guarde Valen, acordate que todo esto es muy manual.
Descargar no hay problema pero compartir en facebook ya es otra cosa, hay que armar un app, explicar en Facebook de que se trata para que te habilten, excede en mucho la dedicacion prevista.
Siempre pueden reenviar el mail que recibieron.
Y el sender del mail que hago ? SOLO puedo mandar "from info@benteveo.tv", cualquier otra cosa no la manda, y esto debe ser por el tema ese que paso hace un tiempo.

**Comment by LeandroBraier** [comment]
1. Ok, en cuanto al "Compartir" podemos poner un link a www.facebook.com y listo?

2. En cuanto al sender, si tenemos el hosting sumateasadia.com.uy no podemos usar un mail con ese dominio? Ahi consulté en un mail a Marce.

**Comment by mkreyness** [comment]
no podemos mandar mails desde Amazon. Y no podemos mandar mails que no sean de la direccion benteveo.tv desde duplika.

**Comment by mkreyness** [comment]
Todo esto "low cost" no es mas que una suma de kilombos.

**Comment by mkreyness** [comment]
No entiendo lo de link a facebook, siempre el link del sharer tiene que tener un AppID, yo ya cree un AppID para lo del Panchismo, puedo usar ese pero no es lo mismo Ironman que Panchismo.

**Comment by LeandroBraier** [comment]
1. Claro, no es lo mismo, pero podemos usar ese AppleId?

2. Entonces creemos un sadia@benteveo.tv. Eso sí se puede? Si es así lo hablo con Eze y te confirmo si es así. Sino vemos la forma de hacerlo desde mailchimp, total la foto va a estar hosteada en un servidor, es un link como eran los de Paty.

**Comment by mkreyness** [comment]
No creo que se pueda de todos modos usar el link DESDE EL MAIL, para eso tiene que haber una pagina de landing separada del mail.
Una cosa es hostear la foto para que aparezca en el mail, y otra hacer una pagina con contenido variable a la que accedan y que para cada uno funcione por separado, Ademas se va a ver el dominio, lo que va a compartir va a ser un URL de "benteveo.tv", no sirve.

**Comment by LeandroBraier** [comment]
1. Tenés razón. Quitemos el botón de compartir y listo. Que esté el botón de Descargar y que la foto misma tenga reaccione también descargando el archivo al hacer clic. Eso se puede?

2. Confirmame si podemos hacer eso.

**Comment by ghost** [comment]
@mkreyness me mandas un mail con exactamente lo que tengo que hacer? Gracias!

**Comment by mkreyness** [comment]
no se puede hacer nada, es un MAIL, no ejecuta codigo, ningun cliente de mail acepta ejecutar codigo por mucho que uno lo ponga,  Hablalo con Fede a ver si se le ocurre algo pero para mi el que se la quiere guardar tiene que hacer click en la foto y darle "Guardar Como...", no hay algo que podamos automatizar.

**Comment by mkreyness** [comment]
Valen: despues te mando.

**Comment by LeandroBraier** [comment]
1. Ok, no entendía eso MK. Ahora lo entiendo. Entonces resolvemos de la siguiente manera: la imagen y el botón de descargar tienen un link que lleva directo a la imagen. ¿Está bien así? URL de la imagen suelta en nuestro servidor. Eso se puede?

**Comment by mkreyness** [comment]
si pero va a decir benteveo.tv, no "sadia", esta bien eso ? Lo mismo que el mail que se manda.
Aunque sea tendriamos que usar un subdominio sadia.benteveo.tv, aunque al cliente eso capaz le parezca peor.

**Comment by LeandroBraier** [comment]
No, eso es mejor todavía! Podemos gestionarlo a eso? Yo decía sadia@benteveo.tv pero info@sadia.benteveo.tv es mejor aún. Confirmame si se puede y empecemos a gestionarlo ya. 

Viste el mailing que le subí a Fede en el ticket: https://github.com/LeandroBraier/Sadia/issues/3 ?

**Comment by FAAREIA** [comment]
Al link a la foto ya le puse para que se la baje, pero la foto tiene que estar en algun servidor. Si es el server de que salen los mails mejor.

**Comment by LeandroBraier** [comment]
@mkreyness ya está el mailing final.

http://www.benteveo.tv/sadia/mailing/ironman/ironman.html

Confirmame si podemos hacer lo de sadia.benteveo.tv y estamos listos.

**Comment by mkreyness** [comment]
Ok, si, supongo que si, es algo que se hace directo en Duplika.
La direccion de las imagenes seria algo asi como
sadia.benteveo.tv/ironman/juan+perez.com.jpg

**Comment by LeandroBraier** [comment]
Perfecto MK. Muchas gracias!

**Comment by mkreyness** [comment]
no anda todavia, si en un par de horas sigue igual, va a haber que reclamar a Duplika.
El ping a sadia.benteveo.tv no da nada.

**Comment by mkreyness** [comment]
ya anda, pero entra en esa porqueria de las marcas que alguna vez hicimos y se complica todo.

**Comment by mkreyness** [comment]
Hice que el sistema te mande un mail con foto, Lean, lo recibiste ?

**Comment by LeandroBraier** [comment]
Si, excelente! Impecable estaba. Ahora le toca a Valen probar el sistema de la foto no?

**Comment by LeandroBraier** [comment]
@valentinsabbath mañana podés venirte a la agencia así vemos esto juntos y lo probamos. Es lo mismo que estás haciendo con la placa de la foto para la activación de Sadia, pero esto es para otra activación de la misma marca.
