### ISSUE TITLE
Mailing Sadia Ironman

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Sadia#3]
@FAAREIA el pedido para este mailing es bien simple. Solo te pido que mantengas en pie lo que @mkreyness necesita para poder hostear o embeber la foto.

DISEÑO

El diseño debería ser este:

![mailing-llegada-ironman](https://cloud.githubusercontent.com/assets/6719872/20566772/13a349e6-b175-11e6-9111-9124778c5f05.png)

EDITABLE
Acá va el editable con todo en smart object e imagen:

[Mailing-Llegada-Ironman.psd.zip](https://github.com/LeandroBraier/Sadia/files/609163/Mailing-Llegada-Ironman.psd.zip)

Fuentes:

[fonts.zip](https://github.com/LeandroBraier/Sadia/files/609005/fonts.zip)

Avisame si se lo podés pasar hoy a MK para que lo trabaje.

abrazo

**Comment by LeandroBraier** [comment]
Actualicé el diseño recién @FAAREIA quitando el botón de compartir.

**Comment by FAAREIA** [comment]
http://www.benteveo.tv/sadia/mailing/ironman/ironman.html
Pruebenlo y cualquier cosa me dicen

**Comment by LeandroBraier** [comment]
Muchas gracias @FAAREIA ! Igual me parece que entendiste un detallecito mal. La foto es solo una foto que incluye el tiempo ya pegado, no hace falta que lo incluyas en el mail por código. Lo mismo el pie de la foto. Ajustás eso porfa?

@mkreyness como lo ves?

**Comment by mkreyness** [comment]
Fede el boton de descargar que va a tener ? Un link a la foto ? Porque codigo no se puede ejecutar en el mail.

**Comment by LeandroBraier** [comment]
Por eso decía yo MK que ese link, al igual que un link que debería tener la imagen en si, lleven a la URL de la imagen. Nada más.

@FAAREIA fijate si podés reemplazar las palabras IRONMAN 70.3 PR ESTE LOGO:

![logo ironman](https://cloud.githubusercontent.com/assets/6719872/20568410/3c4c439c-b17b-11e6-8cfb-52f9c31460f0.png)

http://www.ironman.com/~/media/01e5f889916b435ba8147ffad19de80e/2016%20ironman%2070%203%20punta%20del%20este%20uruguay%20logo%20rev%20230x120.png

Tiene letras amarillas pero quizá si le ponés fondo negro solo al logo queda bien.

**Comment by FAAREIA** [comment]
El link a la foto es eso mismo, un link.
Le saqué lo del tiempo y el footer de la foto.
Cambié el texto por el logo, denle F5

**Comment by LeandroBraier** [comment]
Perfecto @FAAREIA ! Muchas gracias! Lo paso al otro ticket así seguimos todo por ahí.

**Comment by LeandroBraier** [comment]
Buen día @FAAREIA ! Cómo estás?

Me pidieron unos cambios urgentes en este mailing, me darías una mano?

Sería:

1. "Quitar la línea con el "AHORA COMPARTE TU FOTO"

2. Cambiar la frase "Descargar" de abajo por "Descarga tu foto y compartela"

3. Se podrá hacer que el link que tiene ese botón de "Descargar", después de descargar la foto, abra una pestaña con www.facebook.com ? Solo eso?

4. Quitar el footer de "Sadia. Busca Superarte" y poner más chiquito abajo, sobre blanco nuestro habitual "Desarrollado por Benteveo" con el link a nuestra web.

Porfa dale prioridad a esto que lo tenemos que enviar hoy si o si.

abrazo

**Comment by mkreyness** [comment]
1) No seria "descargá tu foto y compartila" ? Quedamos que los uruguayos no hablan de tu.
2) los mails no pueden ejecutar codigo, nunca van a poder abrir algo que no sea lo que la persona clickeo.
3) Ojo cualquier toque Fede que esta en el TEMPLATE ironmanT.html, no en ironman.html (ni en el html2)

**Comment by mkreyness** [comment]
Y Lean: a que hora hay que mandarlos ? Mira que yo hoy recien llego a las 4 a mi oficina, y los tengo que mandar yo.

**Comment by LeandroBraier** [comment]
Ok, los mandaremos a esa hora, no te preocupes, lo importante es tener al menos el de 1 usuario particular enviado antes, que lo puedo enviar por mailchimp.

2. No es posible entonces?

**Comment by mkreyness** [comment]
2- No, no podemos poner en el cuerpo de un mail nada que requiera ejecutar codigo, ningun cliente de mail le da bola.
La unica forma de hacer eso seria con una pagina de landing, algo que no se quiso hacer (base de datos, etc. etc). Poco presupuesto => poca prestacion.

**Comment by LeandroBraier** [comment]
2- Sisi, entiendo. Eso mismo le aclaré a Eze.

Otra pregunta: tenemos varios corredores con un mismo mail, como podemos hacer con el titulo de las imagenes?

**Comment by mkreyness** [comment]
Misma direccion: misma foto. Acordate que es la unica info con que cuento, el nombre del archivo.

**Comment by LeandroBraier** [comment]
Por eso preguntaba.  ¿No se puede poner en distintos envios o agregar un
numero al final que tu sistema no tome? O mandar esos mails aparte? Seran 3
o 4.

**Comment by LeandroBraier** [comment]
@mkreyness te hago una consulta: si agregamos una página ahora que tiene la foto embebida y un botón de Compartir en Facebook:

1) ¿Para cuando pensás que lo podemos tener? Lo necesitamos mandar hoy pero solo a 1 de los corredores.

2) ¿Cuántas horas te llevaría hacerlo? (obviamente la maquetación te viene dada de Fede)

**Comment by FAAREIA** [comment]
1. Hecho
2. Hecho
3. No puede haber 2 links en un mismo link
4. Imagino que es lo que va debajo del video sobre ese fondo blanco, ahora lo puse en HTML por lo que no tiene que ir incluido en la imagen generada.

http://www.benteveo.tv/sadia/mailing/ironman/ironman.html
El template tiene los cambios aplicados

**Comment by LeandroBraier** [comment]
Gracias Fede pero no lo veo bien. Quizá me entendiste mal.

1. La sigo viendo.

2. Te había pedido que diga "Descarga tu foto y compartela". No va voceado como la otra campaña de Sadia porque hay gente de todo el mundo en la carrera.

3. OK.

4. El footer que tenías que quitar y reemplazar por el Desarrollado por Benteveo es el del mailing, no el de la foto que generamos nosotros. Este:

<img width="524" alt="captura de pantalla 2016-11-29 a las 12 45 42 p m" src="https://cloud.githubusercontent.com/assets/6719872/20715317/8c08241c-b62d-11e6-8f71-1044f5c751a6.png">

Porfa lo ajustás?

**Comment by FAAREIA** [comment]
1. F5
2. Hecho
3. Ok
4. Hecho

http://www.benteveo.tv/sadia/mailing/ironman/ironman.html
El template tiene los cambios aplicados

**Comment by LeandroBraier** [comment]
Gracias Fede! Yo sigo viendo que dice "COMPARTE TU FOTO" puede ser? Ya hice F5, borré el caché y todo.

<img width="664" alt="captura de pantalla 2016-11-29 a las 1 06 29 p m" src="https://cloud.githubusercontent.com/assets/6719872/20716299/7daedf52-b630-11e6-9666-c1e1ac1e39c8.png">

Es abajo del logo de Ironman donde te digo.

**Comment by mkreyness** [comment]
Respondiendo a tus preguntas, Lean, si es una unica pagina fija, no requiere de nada mio, le decis a Fede que la arme con la foto que corresponda, le pasas el link al tipo y listo.
Ahora, para hacer algo que funcione con CUALQUIERA, estamos mal, porque no tenemos una base de datos, habria que pasar en el URL el mail de la persona para que sepa que foto mostrar, eso si requeriria de un poco de codificacion, no mucho, pero ahi si empieza a jorobar lo de tener el "+" en el nombre, porque no lo va a procesar bien. Y eso tendria que ir en el mailing ? Hay que hacer un mailing nuevo.

**Comment by LeandroBraier** [comment]
Ok MK. Entonces :

1. Cuanto tiempo te llevaria lo del boton de fb (incluyendo la gestion en
fb para el script) esto lo necesito para saber cuantos dias nos demoraria
el envio a los corredores.

2. Cuantas horas tuyas llevaria esta programación ? Si sacamos lo del mail
automatico y lo hago yo por mailchimp equiparariamos las 5 hs? Decimelo con
honestidad. Eze me lo agregó ahora y yo le dije que te consultaba a vos por
el tema de las horas y las posibilidades técnicas.

**Comment by LeandroBraier** [comment]
Porfa cuando puedas quitalo. Lo sigo viendo.

**Comment by mkreyness** [comment]
No entiendo bien como quedaria todo, vos armarias todo en mailchimp para mandar los mails ? Tendrias que cargar una base de datos de mailchimp a mano, incluyendo los URLs del link a la pagina que serian todos diferentes (incluirian el email del tipo en el URL). En esos mails NO IRIA la foto, puesto que no creo que tengas como subir fotos a una base de datos de mailchimp.

El boton de fb en la pagina es tema de Fede, no lleva programacion. El problema siempre es que si dependemos del sharer FB solo scrapea una vez la pagina y tiene siempre LA MISMA FOTO, no creo que sirva para contenido variable. Esto lo digo cada vez que hacemos una accion asi. 

2. El mail automatico YA LO PROGRAME, lo unico que me estarias liberando es de EJECUTARLO.
No hay problema, la programacion de que la foto dependa del URL son 5 minutos, pero te insisto: NO FUNCIONA compartir en Facebook una pagina fija con contenido variable. Para que sirva, cada pagina tendria que estar grabada en forma independiente (no dependiendo del URL) con contenido fijo, sus og:image tags propias (que Facebook pueda scrappear todas A PRIORI, y es mas habria que entrar a facebook y hacer que escrapee manualmente CADA UNA para estar seguros de que va a funcionar).
Esto si requeriria de una programacion completamente diferente a la hecha hasta ahora, y de mucha mano de obra. Si queres te agrego de administrador de la aplicacion de Sadia y una vez que esten hechas todas las paginas fisicas, le vas haciendo el scrap a c/u desde Facebook...

**Comment by LeandroBraier** [comment]
Marce, entiendo. Te puedo llamar un minuto? Asi lo resolvemos más rápido me
parece.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora <http://benteveo.tv>
Móvil 1158717399

2016-11-29 14:01 GMT-03:00 mkreyness <notifications@github.com>:

**Comment by mkreyness** [comment]
estoy en un cliente... Me voy a las 3.

**Comment by LeandroBraier** [comment]
Dale, a las 15 te llamo. Lo que no entiendo bien es si no podemos poner el
botón de compartir el contenido en la página individual:

. ¿Cómo hicimos para la leyenda paty?

. ¿Cómo vamos a hacer acá? http://www.benteveo.tv/sadia/sitio/video.html Yo
entendí que habías hecho la gestión de una app en Facebook que lo permitía,
no es así?

**Comment by mkreyness** [comment]
Pero esos eran videos, lo que compartian era un LINK, nunca estaban EMBEDDED en sus cuentas de facebook.
Las fotos son otra cosa, porque Facebook las scrapea (los videos no) y realmente las guardan ellos.

**Comment by mkreyness** [comment]
Lo mismo con lo de Sadia, lo que vamos a compartir es un link para que entren a la misma pagina, hasta que no entran no ven el contenido.
NO es lo mismo que la foto, que vos queres que se VEA directo en Facebook.

**Comment by LeandroBraier** [comment]
Ya entendí perfecto MK. Muchas gracias!

Te tiro una alternativa, que es más china para mi pero para vos me parece
que más fácil.

¿Qué pasa si subimos las fotos a un album oculto en nuestro Facebook y que
el botón comparta ese link? (como hacemos en las comunidades de vendedores)

**Comment by LeandroBraier** [comment]
Yo puedo cargar la base de usuarios y demás. Puedo renombrar las imágenes
una vez más también,no hay problema.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora <http://benteveo.tv>
Móvil 1158717399

2016-11-29 14:27 GMT-03:00 Leandro Braier <leandrobraier@gmail.com>:

**Comment by mkreyness** [comment]
pero cada link igual es diferente, y el nombre no tendrias control, tendrias que copiar cada uno (que es un chorizo de letras y numeros) en la base de datos de Mailchimp para que salga c/u.
Salvo que solo compartas EL ALBUM y asi son todos iguales, pero ahi ya haces todo sin mi directamente.

**Comment by FAAREIA** [comment]
Hola Lea, yo lo veo bien online. Dale ctrl+F5 o dale al ícono de refresh del browser.
Más allá de eso, si te sigue pasando que ves la imagen vieja, decime desde donde lo ves al mail, si desde el navegador poniendo la url http://www.benteveo.tv/sadia/mailing/ironman/ironman.html o desde mailchimp o desde un cliente de mail.

Avisenme si necesitan que prepare algo más del mail
Abrazo

**Comment by FAAREIA** [comment]
Landing: @mkreyness 
http://benteveo.tv/sadia/landing/landing.html

Faltaría que me digan la el título de la página, el título de la publicación del facebook y la meta description de la página. @LeandroBraier

**Comment by LeandroBraier** [comment]
Gracias @FAAREIA !

Te paso lo que pedías:

Título de la página: Tu tiempo de llegada en Ironman
Metadescription: Sadia desea felicitarte por tu tiempo de llegada en Ironman 70.3 y por eso te obsequia esta foto para que compartas con amigos.

Título de la publicación en Facebook: Mira mi tiempo de llegada en Ironman 70.3!

Detalles: 

1) Veo al pájaro del logo de Benteveo como caído en una linea por debajo del "Desarrollado por Benteveo. Puede ser?

<img width="378" alt="captura de pantalla 2016-11-29 a las 6 03 09 p m" src="https://cloud.githubusercontent.com/assets/6719872/20727910/0ea987a4-b65a-11e6-9fd4-7f400975a4ce.png">

2) El botón de compartir podrá estar un poco más grande? Si pudiera ser del doble del tamaño actual ideal.

abrazo

**Comment by mkreyness** [comment]
Fede yo ya hice un template con tu primera version y le fui ajustando cosas, por favor lo que modifiques tocalo en /sadia/landing/ironmanT.html

**Comment by mkreyness** [comment]
Ya encontre la forma de forzar el scrape de la pagina recien generada, en forma automatica.
Solo necesitamos tener las fotos y el template definitivo.

**Comment by LeandroBraier** [comment]
Excelente MK!

Las fotos ya están armadas, ahora Valen las está poniendo a subir al
servidor. Si Fede hoy corrije el template mañana a la mañana ya tendríamos
todo para salir no? Decime después como reemplazo los caracrteres para
armar las URL.

**Comment by mkreyness** [comment]
Si.
Todo lo que no sea letras o numeros, reemplazalo por guion.
Ej:
http://sadia.benteveo.tv/landing/marcelo-kreyness-com.html
http://sadia.benteveo.tv/landing/leandro-benteveo-tv.html

**Comment by LeandroBraier** [comment]
Perfecto. Gracias!

**Comment by LeandroBraier** [comment]
Buen día @valentinsabbath @FAAREIA y @mkreyness ! Cómo están? Repaso pendientes:

@FAAREIA últimas correcciones al template: pájaro del logo de Benteveo caído y botón de Compartir más grande.

@valentinsabbath Subir las fotos al servidor

@mkreyness Confirmar que está todo subido en sus respectivas URL como para enviar.

abrazo

**Comment by mkreyness** [comment]
avisenme cuando esten ambas otras cosas y reviso. A partir de ahi genero las paginas definitivas y probamos al azar algunas a ver si las toma bien para el Facebook antes de mandar nada.
Sobre todo es importante que prueben con otros facebooks que no sean el mio, porque yo soy el dueño del App y eso hace que a mi me funcione con privilegios diferentes, lo cual es malo para probar.

**Comment by mkreyness** [comment]
De hecho con los 2 URLs que te pase podrias ya probar vos con tu Facebook Lean.

**Comment by FAAREIA** [comment]
Hecho.
El botón de FB lo agrandé la mitad más.

**Comment by LeandroBraier** [comment]
Perfecto @FAAREIA ! Gracias!

@mkreyness ahi probé los dos links. El tuyo me comparte perfecto. 

<img width="533" alt="captura de pantalla 2016-11-30 a las 10 15 32 a m" src="https://cloud.githubusercontent.com/assets/6719872/20752787/e7cae6cc-b6e1-11e6-85fd-085755327b62.png">

La mia se comparte pero no muestra la imagen, mirá:

<img width="529" alt="captura de pantalla 2016-11-30 a las 10 16 39 a m" src="https://cloud.githubusercontent.com/assets/6719872/20752797/fb358b68-b6e1-11e6-90e8-8b56c8f0f991.png">

Raro, no?

**Comment by FAAREIA** [comment]
Esta desactualizado el open graph igual, cuando se regenere el template debería aparecerte la info nueva

**Comment by LeandroBraier** [comment]
Perfecto entonces. Solo nos falta que @valentinsabbath suba las fotos. Debe estar llegando a Mendoza recién.

**Comment by mkreyness** [comment]
Claro, las paginas NO se regeneran automatico, yo ahora lo corro de nuevo para que se regenere y actualice el opengraph. Prueben en 5 minutos.

**Comment by LeandroBraier** [comment]
@mkreyness te paso la foto a enviarle a fabio.XXXXXX@XXXX.com

![posteo-podio-modificado-2](https://cloud.githubusercontent.com/assets/6719872/20775333/24d9679e-b739-11e6-9587-fccf7fbe26c8.jpg)

**Comment by mkreyness** [comment]
ya la subi y genere la pagina, pero hay un problema, al menos a mi
sadia.benteveo.tv me dejo de andar.
La pagina deberia ser esta:
http://sadia.benteveo.tv/landing/fabio-mariano-brf-br-com.html
pero no anda, tengo que ponerle
http://www.sadia.benteveo.tv/landing/fabio-mariano-brf-br-com.html

Tuve que cambiar tambien todo lo que tiene que ver con facebook para que use el link asi. Es una garcha.
Ya intente 20 veces rescrapear y NO ANDA bien el compartir, no toma la foto.

**Comment by LeandroBraier** [comment]
Justo me metí a probar de casualidad y vi lo mismo. Todo lo demás andaba perfecto y me faltaba el scrapeo nomás. Está seguro que te está rescrapeando? Quizá solo hay que esperar que lo haya automático Facebook, no?

**Comment by mkreyness** [comment]
No solo lo escrapeo yo automatico, sino que lo recontra escrapee a mano 20 veces.
Facebook tiene sus tiempos que uno no puede manejar ni siquiera asi. 
Y yo creo que el haber tenido que switchear de sadia.benteveo.tv a www.sadia.benteveo.tv no mejora mucho las cosas.
Lo que mas bronca me da es que ayer sadia.benteveo.tv andaba perfecto, yo te pase 2 URL asi y todos los vimos. No se de que depende, tal vez habria que pedir asistencia a Duplika.

**Comment by LeandroBraier** [comment]
Ok, porfa me pasás el detalle de qué les tengo que pedir?

Sino les digo: 

**Hola responsable de Duplika: Estábamos usando la URL sadia.benteveo.tv ayer y hoy no nos funciona. ¿Ustedes hicieron alguna modificación en nuestro hosting? Necesitamos que funcione lo antes posible.**

**Comment by LeandroBraier** [comment]
Pará pará. A mi está andando este:

http://sadia.benteveo.tv/landing/fabio-mariano-brf-br-com.html

**Comment by LeandroBraier** [comment]
Probá scrapear este porfa.

**Comment by mkreyness** [comment]
le agregue hace un rato unos registros en el DNS que faltaban, igual tampoco me los mostraba y de hecho en la maquina de casa sigue sin andarme, pero en la de la oficina anda bien.
Ahora nos enfrentamos a otro problema: al scrapear me dice esto:

Provided og:image, http://sadia.benteveo.tv/mailing/ironman/fotos/fabio.mariano%2Bbrf-br.com.jpg could not be downloaded because it exceeded the maximum allowed sized of 8Mb or your server was too slow to respond.

Obviamente no tiene 8Mb, asi que el problema es que a ellos tambien les cuesta acceder a sadia.benteveo.tv

Si lo compartis despues en tu facebook sale bien, pero no hace el preview al momento de compartir.

**Comment by LeandroBraier** [comment]
jajaja Ahi lo probé y funcionó bien pero como vos decís. Siempre nos falta 1 para el peso! Qué te parece si mejor esperamos a ver si lo levanta?

**Comment by LeandroBraier** [comment]
Por casualidad vos podés cambiar la "metadescription"? Yo pensé que era para la página no para la description de la nota de Facebook.

**Comment by mkreyness** [comment]
Si, decime que poner.

**Comment by LeandroBraier** [comment]
Cambiale a: " Les comparto con orgullo esta fotografía de mi llegada, gentileza de Sadía. "

**Comment by mkreyness** [comment]
Va el acento en Sadia ? Ellos nunca lo escriben.

**Comment by LeandroBraier** [comment]
Perdon, tenes razon! Va sin tilde.

**Comment by LeandroBraier** [comment]
Gracias MK!

**Comment by mkreyness** [comment]
ya esta puesto y escrapeado. Parece andar bien.
Vamos a cambiar el resto de las fotos ? Va a pasar mucho tiempo hasta que Valen las genere, yo las levante, las vuelva a subir...  Despues de eso habria que esperar 24 horas a que se refresque todo.

**Comment by LeandroBraier** [comment]
Por que esas 24 hs? No se puede más  scrapear a mano?

El tema es que otra opción tenemos sino, Que yo haga todas las fotos a mano?

**Comment by mkreyness** [comment]
Ya viste que por mucho que se escrapee a mano, Facebook NO levanta la foto en ese momento, 
Una cosa es escrapear (para que se entere que existe) y otra que se molesten en hacer ellos el upload de la foto a su repositorio. En el mejor de los casos ahora puede estar levantada la foto con el tiempo descentrado, las nuevas fotos con el tiempo bien, como se van a llamar igual que antes, tal vez no las levanten NUNCA.
A que te referis con hacer las fotos a mano ?

**Comment by LeandroBraier** [comment]
jeje como hice la de Fabio M pero entiendo lo que decís.

Entonces hagamos eso, que vaya scrapeando las fotos con el tiempo descentrado y después la que se comparta, que se vea bien. Vamos así. Me parece una buena solución, no?

**Comment by LeandroBraier** [comment]
Vos podés creer que ahora no puedo mandar nada porque nos rechazó la tarjeta de crédito? Esto es un verdadero triatlon

**Comment by mkreyness** [comment]
El escrapeo automatico se hace cada vez que yo regenero las paginas, o sea que eso se hizo anoche, proba con cualquiera a ver que sale.
Este proyecto esta mal parido de entrada, como todo lo que se hace "low cost"...

**Comment by LeandroBraier** [comment]
Asi es. Voy a tomar nota igual esta vez y plantearlo de entrada: primero nos piden low cost y después se olvidan de que lo pidieron y quieren hacer lo que tendríamos que haber hecho con tiempo y dinero en dos minutos por 2 mangos. Ahora paciencia jeje Gracias MK! Te aviso cuando tenemos alguna novedad de las fotos corregidas. abrazo
