### ISSUE TITLE
Mail info@sumateasadia.com.uy

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Sadia#4]
@mkreyness empecemos a tramitar un mail info@sumateasadia.com.uy para usar desde Mailchimp (no desde tu sistema automático).

Qué necesito para esto? Si vos me das el mail y una forma de acceder yo puedo hacer que Mailchimp lo verifique y usarlo para la campaña del Panchismo (no la de Ironman).

**Comment by mkreyness** [comment]
pero no podemos hacerlo en Amazon, no tenemos mailserver. Lo que habiamos hecho en su momento con Paty fue algo via GMail for Business o algo asi, hubo que pagarlo por un mes o algo asi y ahi el mail lo hosteaban ellos. TAL VEZ si pudieramos hacer que se deleguen los MX records a MXRoute, podemos manejarlo mejor.
Hay que hablar con MS para que vea como cargarle registros MX a sumateasadia.com.uy que apunten a los DNS de MXRoute.

**Comment by LeandroBraier** [comment]
Ahi le consulté. Gracias!

**Comment by mkreyness** [comment]
me temo que igual habria que pagar.  Termina saliendo mas barato (por ser una cosa de un unico uso) usar lo de GMail for Business.

**Comment by LeandroBraier** [comment]
Y no podemos pedirle algo a Duplika para volver a hacer lo que ya hicimos
con Paty?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora <http://benteveo.tv>
Móvil 1158717399

**Comment by mkreyness** [comment]
Con Paty hicimos esto que te dije de GMail For Business, no fue nada en Duplika.
Simplemente cargamos que el mail de laleyendapaty.cl lo maneje GMail, y cuando Mailchimp mando el mail de verificacion lo pudiste ver desde esa cuenta de GMail.

Lo que yo te puedo hacer sin ningun problema es una casilla sadia@benteveo.tv o sumateasadia@benteveo.tv y la accedes por POP para recibir ese mail.
Pero siempre queda feo.

**Comment by LeandroBraier** [comment]
Ok. Para esto entonces gestionemos el Gmail for Business. Me pasas que es
lo que hay que hacer mediante un link o algo así veo cuanto duele y lo
hablo con Eze mañana?

**Comment by mkreyness** [comment]
Hay que buscar los mails viejos, todo eso ya lo hicimos. Salia algo asi como u$s 5 por mes.

**Comment by LeandroBraier** [comment]
No encuentro nada MK, pero sigamos adelante. Qué necesitás que haga? Creo una cuenta para Sadia en Gmail y contrato Gmail for business? Es eso? O lo hacen uds?

Ahi MS tiró otra propuesta, es posible lo que dice?

**Comment by mkreyness** [comment]
Si, ya te cree la cuenta sumateasadia@benteveo.tv.
Fijate en ese mail la pass.

**Comment by LeandroBraier** [comment]
Perfecto MK! Gracias!
