### ISSUE TITLE
Últimos ajustes Sistema Sadía Panchismo

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Sadia#5]
@mkreyness hicimos un pequeños test con Valen acá y todo funciona bien, salvo dos bugs:

1. Los ingredientes siguen sin quedar limitados a 5 ingredientes.

2. Hay un bug en el countdown que hace que el countdown no aparezca hasta que el proceso de grabación ya murió. 

Me dijo @valentinsabbath que vos ya sabías esto por genero un ticket para que lo sigamos por acá.

abrazo

**Comment by mkreyness** [comment]
limitados quiere decir que te deja poner MAS de 5 ? El control era que no te dejara avanzar si era MENOS de 5, ni siquiera hay previsto un mensaje para cuando pusiste mas.
2- el problema no es en el countdown, es en lo que haga el video que no esta soltando el control, yo ya le conteste a Valen eso, no se si hizo alguna prueba. 

Esta accesible el equipo ?

**Comment by LeandroBraier** [comment]
1. Ah si. Tienen que ser 5 minimo y 5 máximo. Podemos agregar eso?

2. Si, está accesible conectada en la oficina.

**Comment by mkreyness** [comment]
ya esta todo solucionado. Le cambie el cartel por "exactamente 5" cuando hay menos o mas.

**Comment by LeandroBraier** [comment]
Jeje perfecto

**Comment by LeandroBraier** [comment]
@mkreyness y @FAAREIA me confirmaron al fin los ingredientes y los guachos me agregaron uno. Ahora tenemos 11 ingredientes. 

@FAAREIA no nos rompamos mucho la cabeza con el diseño. Pongamos 5 arriba y 6 abajo más chicos. Punto.

ARRIBA IRÍAN:
1. TOMATE 
2. LECHUGA
3. CEBOLLA
4. MORRÓN 
5. HUEVO

ABAJO IRÍAN:
6. ACEITUNAS 
7. PAPAS PAY 
8. MOSTAZA
9. KETCHUP
10. MAYONESA
11. QUESO CREMA

Mañana ya dejemos cerrado el sistema entonces.

abrazo

**Comment by mkreyness** [comment]
pero a mi esto me destroza la logica... Yo los numeraba del 0 al 9.

**Comment by mkreyness** [comment]
Valen, para el 11avo te voy a mandar una "A".
Ademas tengo que correr todos los nombres supongo.
Los archivos se tienen que seguir llamando ingrediente-0, .... ingrediente-9, ingrediente-A (el queso crema).

**Comment by LeandroBraier** [comment]
Te pido mil disculpas MK! Te juro que le pedí a Eze mantenernos en 10 pero fue peleada la lucha con el cliente. El queso crema es cruel. Si te puedo ayudar en algo avisame.

**Comment by mkreyness** [comment]
El problema es que va a haber que hacer testing de todo de nuevo.
Yo por ahora toco lo que hay asumiendo que sean 11, despues Fede fijate como haces para distribuirlo porque es una sola lista ahora, si hay que separarla en 2 listas diferentes tambien tengo que cambiar la logica de eso.

**Comment by mkreyness** [comment]
Listo mis ajustes. 
El queso crema sale en una 3era linea, eso lo va a tener que ajustar Fede.
Fijate Valen que todos los nombres de los ingredientes cambiaron. Lo que aca Lean numero del 1 al 11 entonces van de 0 a 'A'.
Lo que nunca vinieron fueron los svg definitivos.

**Comment by LeandroBraier** [comment]
Muchas gracias MK! Esos SVG hay que buscarlos ahora. Para el video los ingredientes van en texto nomás. Ya lo hablamos hoy con Valen.

abrazo

**Comment by mkreyness** [comment]
ok pero los textos Valen los decodifica de unos numeritos que yo le paso, ahora hay que reintepretarlos segun el nuevo contenido (no solo el hecho de que se agrego 1, todos cambiaron o de nombre o de lugar).

**Comment by FAAREIA** [comment]
Ok lo de los ingredientes. Los íconos finales los busco o nos los pasan?

**Comment by LeandroBraier** [comment]
Buscalos Fede porfa. No hay una estética definida para eso porque solo van a aparecer en esta maquetación. En el video aparecen solo como texto.

**Comment by LeandroBraier** [comment]
@valentinsabbath te paso acá las 

INTRO en 720p con transparencia

https://wetransfer.com/downloads/fb084b303cf8a6557f03469ba98cbae520161130194457/d7dd9e8c38642e6f2777632ff6c9773220161130194457/93f6fb

OUTRO EN 720p (no se puede exportar con audio en mp3, pero si te sigue dando problemas el audio quitaselo directamente y que siga la música que ya tenemos.

[Outro-Clip-Sadia-HD.mp4.zip](https://github.com/LeandroBraier/Sadia/files/622883/Outro-Clip-Sadia-HD.mp4.zip)

INGREDIENTES A INCLUIR BAJO LOS CÓDIGO QUE TE PASÓ MK MÁS ARRIBA:

0. TOMATE 
1. LECHUGA
2. CEBOLLA
3. MORRÓN 
4. HUEVO
5. ACEITUNAS 
6. PAPAS PAY 
7. MOSTAZA
8. KETCHUP
9. MAYONESA
A. QUESO CREMA

abrazo

**Comment by LeandroBraier** [comment]
@valentinsabbath no te olvides de revisar esto para la prueba de mañana. Acá tenés los ingredientes definitivos, la intro y el outro.

**Comment by LeandroBraier** [comment]
@mkreyness consulta: es posible cambiar la imagen de preview de Facebook?

Hubo un tema de derechos con la salchicha y la mancha de especias. Nos pidieron cambiar la portada de FB quitando eso.

Necesitaríamos cambiar el preview, te dejo la imagen para cuando puedas:

![preview-sadia-nueva](https://cloud.githubusercontent.com/assets/6719872/21145199/1e2e093e-c12c-11e6-8d9f-de29a2e385a7.png)

@FAAREIA lo mismo ocurre con el mailing que estamos usando. La salchicha y la mancha debería salir, quedando el diseño como lo ves en este preview. Me avisás cuando puedas ajustarlo? Esto puede ser para el jueves o viernes, todo bien. Pedimos el código por whatsapp como siempre sin problema.

**Comment by LeandroBraier** [comment]
@mkreyness te mandé los videos del sábado, te llegaron?

**Comment by LeandroBraier** [comment]
@mkreyness cómo va? Acá te paso los videos del domingo. 

https://wetransfer.com/downloads/38fcbea5425694d8a4824277be89979b20161213213008/e896771f45228e188fbfd15ca6b7842c20161213213008/95f681

Cuando los tengas subido avisame nomás.

abrazo

**Comment by mkreyness** [comment]
todo subido. el ULTIMO de los videos era muy corto, creo que debe estar corrompido.

**Comment by LeandroBraier** [comment]
dale, todo bien. NO lo envio a ese. Gracias!

**Comment by FAAREIA** [comment]
Hecho, F5

**Comment by LeandroBraier** [comment]
Gracias Fede pero lo cambiaste en el mailing interno, puede ser?

Donde necesitaba que modificaras es en el template que se llama Mailing Sadia Videos Panchismo

Puede ser para el lunes, todo bien.

abrazo

**Comment by FAAREIA** [comment]
Hecho, dale F5

**Comment by FAAREIA** [comment]
Lo cambié en el FTP el archivo, a mailchimp no pude entrar y creo que tampoco lo había visto ahi. Cualquier cosa mañana hablamos por whatsapp y me pasas el código.
Abrazo

**Comment by LeandroBraier** [comment]
Ahi lo vi y quedó perfecto @FAAREIA ! Gracias!!

abrazo grande
