### ISSUE TITLE
Mailing Interno Lanzamiento Campaña Sadia

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Sadia#6]
@FAAREIA te paso para que vayas armando la maquetación de un mailing que nos pide el cliente para Sadia. Es como el que ya hicimos para Paty Uruguay, te acordás? Pero ahora con la estética de la campaña de Sadia Sumate al Movimiento que vos ya tenés.

http://www.benteveo.tv/paty_uy/mailing/interno/ruben-rada.html

El contenido está detallado acá con todos los materiales:

[BRIEFF MAIL PANCHISMO.docx](https://github.com/LeandroBraier/Sadia/files/622655/BRIEFF.MAIL.PANCHISMO.docx)

Solo faltan unas fotos y un video de ejemplo de la activación que van a estar la semana que viene. Yo los 3 días hábiles de la semana que viene no estoy, por eso quiero dejar aprobado el diseño para que Eze solo te mande lo que falte, lo compilas y le mandamos el diseño al cliente directamente.

**Comment by FAAREIA** [comment]
Ok, voy armando el diseño entonces

**Comment by LeandroBraier** [comment]
@FAAREIA cuando puedas confirmame si llegás a tener esto para mañana en algun momento. abrazo

**Comment by FAAREIA** [comment]
Decime que te parece lea:
![sadia-mailing-interno](https://cloud.githubusercontent.com/assets/6184969/20839521/bdd95ec4-b88b-11e6-9306-99f01eeb307f.jpg)

**Comment by LeandroBraier** [comment]
Excelente Fede! Lo mando como maqueta para que me manden los contenidos
finales. Gracias!!

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora <http://benteveo.tv>
Móvil 1158717399

**Comment by LeandroBraier** [comment]
@FAAREIA te paso las correcciones del cliente.

[SINTITULO (1).pptx](https://github.com/LeandroBraier/Sadia/files/628188/SINTITULO.1.pptx)

En la parte del video va este link:

`<iframe width="560" height="315" src="https://www.youtube.com/embed/V8MvpTzwwu8" frameborder="0" allowfullscreen></iframe>`

Yo el lunes no voy a estar, así que te voy a pedir un favorcito:

1) El lunes mandale la versión corregida por mail a Eze y pedile las fotos faltantes para sumar a la acción, así podés completar el mailing y que se lo enviemos al cliente. 

2) Es probable que el cliente nos pida subir el mailing a un template en Mailchimp y compartirselo, así que te lo dejo creado en mailchimp así lo pulís directamente y cuando esté final se lo compartís. El template tiene una opción para hacer share a otro usuario. Te muestro acá como:

![image004](https://cloud.githubusercontent.com/assets/6719872/20850420/d9f68cfc-b8b9-11e6-9e01-8683e42ccb26.jpg)

El mail del cliente para que se lo compartas es: maxidonini@msn.com 

Obviamente si necesitás el código de mailchimp me lo pedís, no hay problema.

abrazo

**Comment by LeandroBraier** [comment]
@FAAREIA recibiste las fotos que envió Eze?

Porfa agregalas al mailing junto con el video, subilo como template a Mailchimp y avisame nomás Yo gestiono el resto.

abrazo

**Comment by FAAREIA** [comment]
No las recibí, el mail salió hace rato?

**Comment by LeandroBraier** [comment]
Ahi te las reenvié. Eze te escribió a @faareia. Te lo reenvié a gmail.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora <http://benteveo.tv>
Móvil 1158717399

**Comment by FAAREIA** [comment]
http://benteveo.tv/sadia/mailing/interno/interno.html
https://us11.admin.mailchimp.com/templates/design?tid=253989

Faltan las imágenes de la vía pública.
Al ser un mailing interno, es todo imágen.

**Comment by LeandroBraier** [comment]
Ahi lo vi Fede. Faltan cosas:

1) En el ppt el cliente pedía que la frase NACIÓ EL PANCHISMO... BLABLA esté arriba de todo, incluso de Sumate al Movimiento. El pack iría al lado de Sumate al Movimiento, no de NACIO EL PANCHISMO.

2) En los grises del medio faltan estas fotos:

<img width="639" alt="captura de pantalla 2016-12-05 a las 5 43 27 p m" src="https://cloud.githubusercontent.com/assets/6719872/20900720/2553450e-bb0e-11e6-92df-3efa5cd81688.png">
<img width="370" alt="captura de pantalla 2016-12-05 a las 5 43 19 p m" src="https://cloud.githubusercontent.com/assets/6719872/20900722/2555da6c-bb0e-11e6-971a-f58fde6988f0.png">
<img width="563" alt="captura de pantalla 2016-12-05 a las 5 43 12 p m" src="https://cloud.githubusercontent.com/assets/6719872/20900724/25571918-bb0e-11e6-89aa-c979b655abac.png">
<img width="296" alt="captura de pantalla 2016-12-05 a las 5 43 07 p m" src="https://cloud.githubusercontent.com/assets/6719872/20900721/2555be74-bb0e-11e6-8692-680b951ff348.png">
<img width="630" alt="captura de pantalla 2016-12-05 a las 5 43 00 p m" src="https://cloud.githubusercontent.com/assets/6719872/20900725/2558e90a-bb0e-11e6-8570-6e95e225e247.png">
<img width="373" alt="captura de pantalla 2016-12-05 a las 5 42 53 p m" src="https://cloud.githubusercontent.com/assets/6719872/20900723/25571166-bb0e-11e6-8b33-d2abca7bc463.png">
<img width="725" alt="captura de pantalla 2016-12-05 a las 5 42 47 p m" src="https://cloud.githubusercontent.com/assets/6719872/20900726/257149f0-bb0e-11e6-98d2-74ca46f733b1.png">

(perdón que no te las pasé antes, no las tenía)

Con esto estamos.

abrazo

**Comment by FAAREIA** [comment]
Fijate ahi lea, los afiches no se ven muy bien porque tienen mucho reflejo. Capas que podemos ver de hacerles algo pero la veo jodida
Avisame
Abrazo

**Comment by LeandroBraier** [comment]
Yo los veo bien Fede!! Gracias!! Vamos a ver qué dicen ellos.

abrazo
