### ISSUE TITLE
Nueva tanda de Videos Sábado 17

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Sadia#7]
@mkreyness querido ya tenemos nueva tanda:

https://wetransfer.com/downloads/49441d79dfcade923eb9722af4a39f7d20161220170458/d0b2507570047caca53e8500c051d84920161220170458/5b2056

Me avisás cuando esté subida porfa?

**Comment by mkreyness** [comment]
Avisare, por ahora estoy en la calle

**Comment by mkreyness** [comment]
ya esta subida

**Comment by LeandroBraier** [comment]
Gracias MK!!
