### ISSUE TITLE
Nueva tanda de videos Domingo 18

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/Sadia#8]
Buen día @mkreyness : ya tenemos los videos del domingo 18. Avisame cuando esté arriba.

https://wetransfer.com/downloads/b0d2730f5bfddfefa5440a88420e7bf020161221222512/f50afbcfacc11cf37b3ce170fa7b720620161221222512/696f16

abrazo y gracias!

**Comment by mkreyness** [comment]
listo, ya estan subidos y procesados.

**Comment by LeandroBraier** [comment]
Gracias MK!! abrazo grande
